name: Update Star History

on:
  schedule:
    - cron: '15 6 * * *'

  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create assets directory
        run: mkdir -p assets

      - name: Generate Star History
        uses: xpzouying/star-history@v1
        with:
          branch: star-history
          commit-message: 'chore: update star history chart'
